development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-task-dev
  pool: 5
  username: vagrant
  password: vagrant

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-task-dev
  pool: 5
  username: vagrant
  password: vagrant
